spin_manifest_version = 2

[application]
name = "getcart"
version = "0.1.0"
description = "Get items from the shopping cart Redis"

[[trigger.http]]
route = "/..."
component = "getcart"

[component.getcart]
source = "target/wasm32-wasi/release/get_cart.wasm"
allowed_outbound_hosts = ["redis://unicorn-valkey-master.default.svc.cluster.local:6379"] # Add your Redis host here
[component.getcart.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[variables]
valkey_host = { required = true }
valkey_password = { required = true }

[component.getcart.variables]
valkey_host = "{{ valkey_host }}"
valkey_password = "{{ valkey_password }}"