spin_manifest_version = 2

[application]
name = "addtocart"
version = "0.1.0"
description = "add items to cart microservice"

[[trigger.http]]
route = "/..."
component = "addtocart"

[component.addtocart]
source = "target/wasm32-wasi/release/add_to_cart.wasm"
allowed_outbound_hosts = ["redis://unicorn-valkey-primary.default.svc.cluster.local:6379"] # Add your Redis host here
[component.addtocart.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[variables]
valkey_host = { required = true }
valkey_password = { required = true }

[component.addtocart.variables]
valkey_host = "{{ valkey_host }}"
valkey_password = "{{ valkey_password }}"